### ISSUE TITLE
Some confusion about the calculated progress of diffusion matrix in utilities.py

### ISSUE THREAD

**Issue by ZongweiZhou1** [ZhuangCY/DGCN#1]
Hey, @ZhuangCY 

This is an impressive job. But I find the diffusion matrix in utilities.py is calculated by normalizing adjacent matrix plu PPMI, rather than just PPMI.
I dont find related description in the paper, could you tell me why deal it in such a way? dose it have some performace improved?

**Comment by ZhuangCY** [comment]
Hi, Zongwei

Please refer to the Test.py file. To obtain the Adjacency Matrix and PPMI matrix, we call these two functions:
1. diffusions = diffusion_fun_sparse(adj.tocsc())
2. ppmi = diffusion_fun_improved_ppmi_dynamic_sparsity(adj, path_len=2, k=1.0)

As for your question, there does be a function (i.e., diffusion_fun_improved()) to calculate the normalized adjacency plus PPMI matrices. If I remember correctly, in experiments, I tried different ways to get the different diffusion matrices. This function may be one of the tries. And, we did not use it in the final model.  

If you have any further concern, please feel free to ask. Thanks very much for your interests.
